### ISSUE TITLE
您好,ios真机上能通过吗?

### ISSUE THREAD

**Issue by sanruby** [LastLeaf/miniprogram-rust-wasm-example#1]
您好,ios真机上能通过吗?

**Comment by LastLeaf** [comment]
可以的。

**Comment by sanruby** [comment]
谢谢回复,iOS真机断开微信小程序开发工具后,得新启动小程序,加载过程出现
Error loading Rust wasm module 'demo': <ReferenceError: Can't find variable: WebAssembly>
2 (in promise) MiniProgramError
Can't find variable: WebAssembly
at WebAssembly (demo.js:75:28)
at (WASubContext.js:2:66139)
at (WASubContext.js:2:66247)
at e (WASubContext.js:2:68700)
at (WASubContext.js:2:32938)
at r (WASubContext.js:2:32637)
at h (WASubContext.js:2:111445)
at (WASubContext.js:2:112266)
at (WASubContext.js:2:94559)
at (WASubContext.js:2:101100)
_onNativeTimer
global code
请教这个是什么原因?Android真机正常.有微信的联系的方式么?我的微信号:929098991

**Comment by LastLeaf** [comment]
第2步转换为 js 之后，应该就不会再调用 WebAssembly 了。这一步失败了。

可以参考我的公众号文章上面对每一步的解释来分析问题。
